<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Student_registration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Account\resetpasswordview.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Account\resetpasswordview.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Views\Account\resetpasswordview.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Account\resetpasswordview.cshtml" />
  </ItemGroup>

</Project>
